// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqRL1JUfHzrjNKAC4vwPna4Rs0iEtgYg',
    appId: '1:910206601075:web:f1e89fed2864dd9d6fa706',
    messagingSenderId: '910206601075',
    projectId: 'car-accessory-dit',
    authDomain: 'car-accessory-dit.firebaseapp.com',
    storageBucket: 'car-accessory-dit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm9GLoyOdqN8NNjykRb8CeqvK91NXwFHw',
    appId: '1:910206601075:android:f04ebd0952016c746fa706',
    messagingSenderId: '910206601075',
    projectId: 'car-accessory-dit',
    storageBucket: 'car-accessory-dit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmv6y5znl450sRcJGwWmAzFEmwx8_iFqs',
    appId: '1:910206601075:ios:4927e4ed79c8b8f06fa706',
    messagingSenderId: '910206601075',
    projectId: 'car-accessory-dit',
    storageBucket: 'car-accessory-dit.firebasestorage.app',
    iosBundleId: 'com.example.carAccessories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmv6y5znl450sRcJGwWmAzFEmwx8_iFqs',
    appId: '1:910206601075:ios:4927e4ed79c8b8f06fa706',
    messagingSenderId: '910206601075',
    projectId: 'car-accessory-dit',
    storageBucket: 'car-accessory-dit.firebasestorage.app',
    iosBundleId: 'com.example.carAccessories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqRL1JUfHzrjNKAC4vwPna4Rs0iEtgYg',
    appId: '1:910206601075:web:5bf77c61077021fa6fa706',
    messagingSenderId: '910206601075',
    projectId: 'car-accessory-dit',
    authDomain: 'car-accessory-dit.firebaseapp.com',
    storageBucket: 'car-accessory-dit.firebasestorage.app',
  );

}